### ISSUE TITLE
Missing recipe - Berry Vinaigrette Salad [1.12.2za]

### ISSUE THREAD

**Issue by BladeVanZ** [MatrexsVigil/harvestcraft#296]
![screen shot 2018-11-25 at 3 57 23 pm](https://user-images.githubusercontent.com/44985391/48977448-df96d980-f0cc-11e8-8f3d-a22efce1ddc0.png)

"Clicking furiously for recipe"

Issue: Recipe seem to be missing

Version: 
Pam's HarvestCraft 1.12.2za
Forge 1.12.2 - 14.23.5.2768

**Comment by MatrexsVigil** [comment]
Fixed in upcoming 1.12.2zd

**Comment by corgiblu** [comment]
Hey! Just letting you know this issue is still there. The recipe named "harvestcraft:berryvinaigrettesaladitem" actually outputs 3 pizza slices. Also conflicts with Edible root recipe. (Using version 1.12.2zd btw.)
