### ISSUE TITLE
[1.12] Nearly all recipes missing

### ISSUE THREAD

**Issue by NielsPilgaard** [MatrexsVigil/harvestcraft#4]
Heya!

I just downloaded the newest update, and I'm afraid the majority of items don't have recipes, for me atleast. I found recipes for 4 items with Zucchini in them, and one other large-ish meal - There are probably a few more.
This was tested in a custom instance with only JEI and Pam's Harvestcraft.

Minecraft 1.12
Pam's Harvestcraft 1.12a
Forge 1.12 14.21.1.2426

**Comment by trilexcom** [comment]
hi Pam

Thanks for your food mod i really love Pams HarvestCraft i updated to 1.12 alpha i know its still alpha version i tested your newest version i still dont see any recipes except for the above.

i did delete the config file to regenerate a new config still no recipes 

no rush just wanted to come in your github and let you know 

Have a wonderful Day or Night! 

Thanks 

Mat (TrilexCom)

My Forge Version is 2426
Pams Version is 1.12a

**Comment by Aalwein** [comment]
Same as above, just downloaded the new 1.12a after seeing the Reddit post.

**Comment by MatrexsVigil** [comment]
Thanks guys.  I'll keep working on it!

**Comment by trilexcom** [comment]
Thank you

**Comment by MatrexsVigil** [comment]
I'm closing this since I released 1.12b which has a lot more (maybe all) recipes fixed.  If you find specific recipes you can't craft in the crafting grid (not just can't see them in JEI/etc), please open a new issue.

Thanks!

**Comment by NielsPilgaard** [comment]
Will do, thank you for the quick update :)

**Comment by MokahTGS** [comment]
1.12b is still missing a ton of recipes.  https://github.com/MatrexsVigil/harvestcraft/issues/7
